# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            Hyeyeon
tagline:          'A Jekyll theme'
description:      'I'm Hyeyeon, interested in E-commerce and Product Management. Contact me <a href="imyeonn@gmail.com" target="_blank">imyeonn@gmail.com</a>.'
url:              https://imyeonn.github.io/
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Hyeyeon
  email:             imyeonn@gmail.com

# Custom vars
version:             1.0.0


# 추가 내용
disqus:           true
